openapi: 3.0.3

info:
  title: AMZ API
  description: API for integrations with amz-server.
  contact:
    url: git@github.com:Inauon/amz-server.git
  version: 0.1.0

servers:
  - url: https://us-central1-amz-server-cb50d.cloudfunctions.net/app
    description: Sandbox

tags:
  - name: customer # <--- unique tag name
    description: Operations to manage the customers
  - name: customer-address
    description: Operations to manage the customers addresses
  - name: customer-address-detail
    description: Operations to manage the detail of customers addresses
  - name: coupon
    description: Operations to manage the coupons
  - name: product
    description: Operations to manage the products
  - name: product-group
    description: Operations to manage product groups
  - name: employee
    description: Operations to manage the employees

paths:
  $ref: "paths.yml"

components:
  $ref: "components.yml"
